<?php
$apiKey="rzp_test_YihG54pkSWIIqk";
include('../connect.php');
session_start();
$session=$_SESSION['id'];
$sqlii="SELECT tbl_reg.loginid,tbl_reg.name,tbl_reg.phone,tbl_reg.email,tbl_reg.address,tbl_reg.id,crimedetails.detailid,crimedetails.charge,crimedetails.logid from crimedetails join tbl_reg on crimedetails.logid=tbl_reg.loginid where tbl_reg.loginid='$session'";
$result = mysqli_query($con, $sqlii);
while ($rows = mysqli_fetch_array($result)) {
    $vi=$rows['name'];
    $ar=$rows['detailid'];
	$email=$rows['email'];
	$phone=$rows['phone'];



 }
$sr="SELECT charge FROM crimedetails where crimedetails.logid='$session'";
$tt=mysqli_query($con,$sr);
while ($rows = mysqli_fetch_array($tt)) {
   // $id= $row['id'];
    $amount=$rows['charge'];
    // $name=$row['name'];

}
?>
<!DOCTYPE html>
<html>
<head>
<title>Women Empowerment</title>
<!-- for-mobile-apps -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Privatio Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
		function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- //for-mobile-apps -->
<link href="css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
<link href="css/style.css" rel="stylesheet" type="text/css" media="all" />
<!-- js -->
<script src="js/jquery-1.11.1.min.js"></script>
<!-- //js -->
<link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
<link href='//fonts.googleapis.com/css?family=Marcellus' rel='stylesheet' type='text/css'>
<!-- start-smoth-scrolling -->
<script type="text/javascript" src="js/move-top.js"></script>
<script type="text/javascript" src="js/easing.js"></script>
<script type="text/javascript">
	jQuery(document).ready(function($) {
		$(".scroll").click(function(event){		
			event.preventDefault();
			$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
		});
	});
</script>
<!-- start-smoth-scrolling -->
</head>	
<body>
<!-- header -->
	<div class="header">
		<div class="container">
			<nav class="navbar navbar-default">
				<!-- Brand and toggle get grouped for better mobile display -->
				<div class="navbar-header">
				  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				  </button>
					<div class="">
						<a class="navbar-brand" href="index.php">Welcome<span>Women Area</span></a>
					</div>
				</div>

				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse nav-wil" id="bs-example-navbar-collapse-1">
					<nav class="link-effect-12" id="link-effect-12">
						<ul class="nav navbar-nav">
						<li class="active"><a href="userindex.php"><span>Home</span></a></li>
							<li><a href="reportcase.php"><span>Report Case</span></a></li>
                            <li><a href="viewbill.php"><span>Case Bill</span></a></li>
							<li><a href="casehistory.php"><span>Case History</span></a></li>
							<li><a href="viewcases.php"><span>Approved Cases</span></a></li>
							<li><a href="rejectcase.php"><span>Rejected Cases</span></a></li>
								<!--<li><a href="viewawarenessprograms.php"><span>Awareness programs</span></a></li>
								<li><a href="viewrights.php"><span>Rights</span></a></li>-->
							<!--<li><a href="../logout.php"><span>Logout</span></a></li>-->
						</ul>
					</nav>
				</div>
				<!-- /.navbar-collapse -->
			</nav>
<!-- header -->

<form method="POST" action="payment.php?amount=<?php echo $amount; ?>&&ar=<?php echo $ar; ?>">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $apiKey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php echo $amount * 100; ?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-order_id="<?php rand(100000, 999999);?>"// Replace with the order_id generated by you in the backend.
    data-buttontext="Pay Amount"
    data-name="Women Empowerment"
    data-description="Add more colors to your day"
    data-image=""
    data-prefill.name="<?php echo $vi;?>"
    data-prefill.email="<?php echo $email;?>"
	data-prefill.contact="<?php echo $phone;?>"
    data-theme.color="#F37254"
></script>
<input type="hidden" custom="Hidden Element" name="hidden">
<!-- <input type="hidden" name="artist" value="<?php echo $ar; ?>">
<input type="hidden" name="amount" value="<?php echo $amount; ?>"> -->
</form>